backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "test"
    label: "Test"
    files:
      - file: "index.html"
        label: "Homepage"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }